---
- hosts:
    - wazimap-ng
  become: yes
  roles:
    - dokku_bot.ansible_dokku
    - ansible-modules-bitwarden

  vars:
    instance_name: "wazimap-ng-{{ env_name }}"
    app_name: "{{ instance_name }}"
    dokku_daemon_install: false # We install this using a dedicated playbook
    dokku_plugins:
      - name: letsencrypt
        url: https://github.com/dokku/dokku-letsencrypt.git
      - name: redis
        url: https://github.com/dokku/dokku-redis.git redis

  tasks:

    - name: "Dokku app exists"
      dokku_app:
        app: "{{ app_name }}"
      tags:
        - app

    - name: "Install RDS CA Cert"
      ansible.builtin.copy:
        src: ../../files/certs/rds-ca-2019-root.pem
        dest: /var/
        owner: root
        group: root
        mode: '0644'
      tags:
        - app

    - name: "Mount RDS Certificate Authority Certificate where postgres expects it - deploy phase"
      dokku_docker_options:
        app: "{{ app_name }}"
        phase: deploy
        option: "-v /var/rds-ca-2019-root.pem:/root/.postgresql/root.crt"
      tags:
        - app
    - name: "Mount RDS Certificate Authority Certificate where postgres expects it - run phase"
      dokku_docker_options:
        app: "{{ app_name }}"
        phase: run
        option: "-v /var/rds-ca-2019-root.pem:/root/.postgresql/root.crt"
      tags:
        - app

    - name: "Dokku app config is set"
      vars:
        postgres_password: "{{ lookup('bitwarden', 'POSTGRES', collection='project/wazimap-ng/' ~ env_name, field='fields.password')}}"
        postgres_hostname: "{{ lookup('bitwarden', 'POSTGRES', collection='project/wazimap-ng/' ~ env_name', field='fields.hostname')}}"
        postgres_username: "{{ lookup('bitwarden', 'POSTGRES', collection='project/wazimap-ng/' ~ env_name', field='fields.username')}}"
        postgres_database: "{{ lookup('bitwarden', 'POSTGRES', collection='project/wazimap-ng/' ~ env_name', field='fields.database')}}"
      dokku_config:
        app: "{{ app_name }}"
        config:
          AWS_ACCESS_KEY_ID: "{{ lookup('bitwarden', 'AWS', collection='project/wazimap-ng/' ~ env_name', field='fields.ACCESS_KEY_ID')}}"
          AWS_S3_REGION_NAME: "eu-west-1"
          AWS_SECRET_ACCESS_KEY: "{{ lookup('bitwarden', 'AWS', collection='project/wazimap-ng/' ~ env_name', field='fields.SECRET_ACCESS_KEY')}}"
          AWS_STORAGE_BUCKET_NAME: "{{ aws_storage_bucket_name }}"
          DATABASE_URL: "postgis://{{ postgres_username }}:{{ postgres_password }}@{{ postgres_hostname }}:5432/{{ postgres_database }}?sslmode=verify-full"
          DJANGO_DEFAULT_FILE_STORAGE: "storages.backends.s3boto3.S3Boto3Storage"
          DJANGO_CONFIGURATION: "Production"
          DJANGO_DEBUG: "False"
          DJANGO_SECRET_KEY: "{{ lookup('bitwarden', 'DJANGO', collection='project/wazimap-ng/' ~ env_name', field='fields.SECRET_KEY')}}"
          DJANGO_SERVER_INSTANCE: "{{ env_name }}"
          DOKKU_LETSENCRYPT_EMAIL: "webapps@openup.org.za"
          PORT: "8000"
          Q_CLUSTER_RECYCLE: "1"
          RUN_COLLECTSTATIC: "Yes"
          RUN_GUNICORN: "Yes"
          RUN_MIGRATIONS: "Yes"
          RUN_QCLUSTER: "Yes"
          SENTRY_DSN: "https://aae3ed779891437d984db424db5c9dd0@o242378.ingest.sentry.io/5257787"
          SERVER_INSTANCE: "{{ env_name }}"
          EMAIL_HOST: "{{ lookup('bitwarden', 'SMTP', collection='project/wazimap-ng/' ~ env_name', field='fields.hostname') }}"
          EMAIL_HOST_USER: "{{ lookup('bitwarden', 'SMTP', collection='project/wazimap-ng/' ~ env_name', field='fields.username') }}"
          EMAIL_HOST_PASSWORD: "{{ lookup('bitwarden', 'SMTP', collection='project/wazimap-ng/' ~ env_name', field='fields.password') }}"
          DEFAULT_FROM_EMAIL: "support@wazimap.co.za"
          STAFF_EMAIL_ADDRESS: "support@wazimap.co.za"
      tags:
        - app

    - name: "Dokku app domains are configured"
      dokku_domains:
        app: "{{ app_name }}"
        domains:
          - "{{ app_domain }}"
      tags:
        - app

    - name: Ensure default port mapping doesn't exist
      dokku_ports:
        app: "{{ app_name }}"
        mappings:
          - http:80:5000
        state: absent
      tags:
        - app

    - name: Dokku proxy ports are configured
      dokku_ports:
        app: "{{ app_name }}"
        mappings:
            - http:80:8000
      tags:
        - app

    - name: "App nginx directory exists"
      file:
        path: "/home/dokku/{{ app_name }}/nginx.conf.d"
        state: directory
        mode: '0755'
        owner: dokku
        group: dokku
      tags:
        - app

    - name: Upload file size is configured
      copy:
        content: "client_max_body_size 1000M;"
        dest: "/home/dokku/{{ app_name }}/nginx.conf.d/client_max_body_size.conf"
        owner: dokku
        group: dokku
        mode: "0644"
      register: nginx
      tags:
        - app

    - name: Nginx is reloaded
      service:
        name: nginx
        state: reloaded
      when: nginx.changed
      tags:
        - app

    - name: "Your dokku git remote"
      debug:
        msg: "dokku@{{ inventory_hostname }}:{{ app_name }}"
      tags:
        - app
