---
- hosts: dokkus
  become: yes
  become_method: sudo
  pre_tasks:
    - name: Set timezone to UTC
      timezone:
        name: UTC
      register: timezone
    - name: restart crond if timezone changes
      service:
        name: crond
        state: restarted
        enabled: yes
      when: timezone.changed
    - name: Set up a unique hostname
      hostname: name={{ inventory_hostname }}
    - name: Set up unattended-upgrades
      apt:
        update_cache: yes
        name: unattended-upgrades
        state: present
    - name: Generate SSH keys
      shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
      args:
        creates: /root/.ssh/id_rsa
  roles:
   - role: dokku_bot.ansible_dokku
     vars:
       dokku_users:
       - name: JD
         username: jdb
         ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC2Xjs+qEWPTBn1Wv0LBVk5mj95GezlE1luuGid09HawiWqXvBP2NP8ywGJKtzqP6+aRUfyyK5BHx/N8V9Sa2clkmEQmYq+lHiyhnA/1wLIu4ISYdivJk7bttMMzVyD95slo6v6uq91cMFozZTNSbmWmaGzdxFLYA4M56LLNrBxyYImrfBzAo7X27Wxj5XCeXlPheDTxZ3evlHQL4u8HJyWv04VYHrmNH86G0iV3xxQbTEdject0KOhJOsaLY+9KpLT7JrH2D8xDRohJWR0I9NssZ2LtjVpuWAG/foKizAGYeQdlySTr11bW+qxxZz+j1MGS9NQhypC/8eKy3fbHyM+LKsidAbnlHZbp/L/wEtU8MbJKjkEzVsNA206ou6NHPFJZ57MCrnqsRg9ttPglomjSdBCY+hmrEH6+44vXSZ8rNZiPn6A39vBvkqxS35DiKuk62BRnNErjJY6k0zrDwTcFFGe3tAEX8ehmZW34uiyGHBSVvQcK0X9SzrY7uEY48PBiznc65IAXiMmqswpW96ezxr/ZfSb50ddR5xVLLjVmUD3du2+nCym/g+k56oWCSrDikXnn5fLRwBCRWQ8Jc8kW8ZDkJ2kKcRAI0HxFijH+foEB293BlQSeoMjU+AjxyK6OGdpcz5hFIlVlDjUs58djUaLKZOOMBPWGqbh5qOHfw== jbothma@gmail.com
       - name: Lunga
         username: lunga
         ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLX3g0/GFUCXHhv8rEGO36h4XoxKLPtrQkLHD1vNglBWGgeXGCMZ4ZfCjjWweb1Bd7BuJ+UCWhun0seqETetLbGsqcMPVpPl981ztrYT56Jp3dgzC4czq6ssW0PXeTUCSCsJy06y2j3b40MnhD/wNhr7sQ5PmF21QVyXSLFN2pHmUgF1umWL1NtIo3M+qFMFARc8OiKOnqMyMGW3kec1cl/Wt/d/1Q3QDWtIrmLM59S0qilDIAIknIPwAv3+oPmiE7Q7L++1/Uj6x6fl7mPW4tTmxk+s9cXIq55k9Y7fSgka30HN8Zs5loeJO02N8kvS/o4wAgPvfS1F5GmJBtlBBp lunga@complex-laptop
