---
- hosts: dokkus
  become: yes

  vars:

  pre_tasks:
    - name: "generate dokku_users"
      set_fact:
       dokku_users: "{{ dokku_users|default([]) + [{'name': item, 'username': item,  'ssh_key': lookup('file', 'files/'+ item + '.key.pub')}] }}"
      with_items: "{{ all_hosts_admins + host_extra_admins }}"
      tags:
        - dokku-ssh-keys

    - name: Make sure /var/log/dokku directory exists
      file:
        path: /var/log/dokku
        owner: syslog
        group: dokku
        mode: 0775
        state: directory

    - name: Make sure that dokku log files exist with correct ownership
      file:
        path: "/var/log/dokku/{{ item }}"
        owner: syslog
        group: dokku
        mode: 0664
        state: touch
      with_items:
        - letsencrypt.log
        - events.log
        - dokku-daemon.log

    - name: Set timezone to UTC
      timezone:
        name: UTC
      register: timezone

    - name: Set up a unique hostname
      hostname: name={{ inventory_hostname }}

    - name: Set up unattended-upgrades
      apt:
        update_cache: yes
        name: unattended-upgrades
        state: present

    - name: Generate SSH keys
      shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
      args:
        creates: /root/.ssh/id_rsa

  roles:
   - role: dokku_bot.ansible_dokku

  tasks:

    - name: "Default packages are installed"
      apt:
        pkg:
          - emacs-nox
          - htop
          - screen
