all:
  hosts:
    pmg5-aws.openup.org.za:
      host_extra_admins:
        - delenamalan
    pmg4-aws.openup.org.za:
      host_extra_admins:
        - delenamalan
  children:
    elasticsearch:
      hosts:
        docker1.code4sa.org:
    discourse:
      hosts:
        docker2.code4sa.org:
    dokkus:
      hosts:
        dokku4.code4sa.org:
        dokku5.code4sa.org:
        dokku6.code4sa.org:
        dokku7.code4sa.org:
        dokku8.code4sa.org:
        dokku9.code4sa.org:
        pmg3.openup.org.za:
        pmg4-aws.openup.org.za:
        pmg5-aws.openup.org.za:
        treasury3.openup.org.za:
          ansible_user: ubuntu
        opencourts.org.za:
        hetzner1.openup.org.za:
          host_extra_admins:
            - zac
            - delenamalan
    pmg:
      hosts:
        pmg5-aws.openup.org.za:
        pmg4-aws.openup.org.za:

  vars:
    all_hosts_admins:
      - jdb
      - adi
      - lunga
    host_extra_admins: [] # Empty default - override this on specific hosts.
