all:
  hosts:
  children:
    elasticsearch:
      hosts:
        docker1.code4sa.org:
    discourse:
      hosts:
        docker2.code4sa.org:
    dokkus:
      hosts:
        dokku4.code4sa.org:
          ansible_user: ubuntu
        dokku5.code4sa.org:
          ansible_user: ubuntu
        dokku6.code4sa.org:
          ansible_user: ubuntu
        dokku7.code4sa.org:
          ansible_user: ubuntu
        dokku8.code4sa.org:
          ansible_user: ubuntu
        dokku9.code4sa.org:
          ansible_user: ubuntu
        pmg3.openup.org.za:
          ansible_user: ubuntu
        treasury1.openup.org.za:
          ansible_user: ubuntu
        treasury3.openup.org.za:
          ansible_user: ubuntu
        hetzner1.openup.org.za:
          host_extra_admins:
            - zac
            - delenamalan
