all:
  hosts:
  children:
    elasticsearch:
      hosts:
        docker1.code4sa.org:
    discourse:
      hosts:
        docker2.code4sa.org:
    dokkus:
      hosts:
        dokku5.code4sa.org:
        dokku7.code4sa.org:
        dokku8.code4sa.org:
        dokku9.code4sa.org:
        pmg4-aws.openup.org.za:
          host_extra_admins:
            - delenamalan
        treasury1.openup.org.za:
        treasury3.openup.org.za:
          ansible_user: ubuntu
        hetzner1.openup.org.za:
          host_extra_admins:
            - zac
            - delenamalan
  vars:
    all_hosts_admins:
      - jdb
      - adi
      - lunga
      - dean
    host_extra_admins: [] # Empty default - override this on specific hosts.
