all:
  hosts:
  children:
    elasticsearch:
      hosts:
        docker1.code4sa.org:
    discourse:
      hosts:
        docker2.code4sa.org:
    dokkus:
      hosts:
        dokku4.code4sa.org:
        dokku5.code4sa.org:
        dokku6.code4sa.org:
        dokku7.code4sa.org:
        dokku8.code4sa.org:
        dokku9.code4sa.org:
        pmg3.openup.org.za:
        treasury3.openup.org.za:
        opencourts.org.za:
        hetzner1.openup.org.za:
          host_extra_admins:
            - zac
