---
- hosts: all
  become: yes

  vars:

  pre_tasks:
    - name: Set timezone to UTC
      timezone:
        name: UTC
      register: timezone

    - name: Set up a unique hostname
      hostname: name={{ inventory_hostname }}

    - name: Set up unattended-upgrades
      apt:
        update_cache: yes
        name: unattended-upgrades
        state: present

  tasks:

    - name: "Default packages are installed"
      apt:
        pkg:
          - emacs-nox
          - htop
          - screen
