- hosts: all
  become: yes
  become_method: sudo
  vars:
    all_hosts_admins:
      - jdb
      - adi
      - lunga
  tasks:
    - name: Ensure group "admin" exists
      group:
        name: admin
        state: present

    - name: "Create user accounts and add users to groups"
      user:
        name: "{{ item }}"
        groups: "admin,www-data"
      with_items: "{{ all_hosts_admins + host_extra_admins }}"

    - name: "Add authorized keys"
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
      with_items: "{{ all_hosts_admins + host_extra_admins }}"

    - name: "Allow admin users to sudo without a password"
      lineinfile:
        dest: "/etc/sudoers" # path: in version 2.3
        state: "present"
        regexp: "^%admin"
        line: "%admin ALL=(ALL) NOPASSWD: ALL"
