all:
  hosts:
  vars:
    env_name: dev
    all_hosts_admins:
      - jdb
      - adi
      - lunga
      - dean
    host_extra_admins: [] # Empty default - override this on specific hosts.

  children:
    dokkus:
      hosts: {}
