all:
  hosts:
  vars:
    env_name: prod
    all_hosts_admins:
      - jdb
      - adi
      - dean
      - juriejan
    all_hosts_remove_admins:
      - lunga
    host_extra_admins: [] # Empty default - override this on specific hosts.
    host_remove_extra_admins: [] # Empty default - override this on specific hosts.
  children:
    elasticsearch:
      hosts:
        docker1.code4sa.org:
    discourse:
      hosts:
        docker2.code4sa.org:
    dokkus:
      hosts:
        dokku5.code4sa.org:
        dokku7.code4sa.org:
        dokku8.code4sa.org:
        dokku9.code4sa.org:
        muni-portal-aws1.openup.org.za:
        pmg4-aws.openup.org.za:
          host_extra_admins:
            - delenamalan
        pmg1-hetzner.openup.org.za:
          host_extra_admins:
            - delenamalan
        treasury1.openup.org.za:
        treasury3.openup.org.za:
          ansible_user: ubuntu
        treasury4.openup.org.za:
        hetzner1.openup.org.za:
          host_extra_admins:
            - zac
            - delenamalan

    muni-portal-backend:
      hosts:
        muni-portal-aws1.openup.org.za:
      vars:
        app_domain: muni-portal-backend.openup.org.za
        env_name: prod

    "peoples-assembly":
      hosts:
        pmg1-hetzner.openup.org.za:

    "vulekamali":
      hosts:
        # treasury3.openup.org.za: Not managed by ansible
        treasury4.openup.org.za:
          gunicorn_workers_arg: "--workers 2"
      vars:
        app_domain: vulekamali.gov.za
        ckan_domain: data.vulekamali.gov.za
        comments_enabled: "true"
        default_from_email: "info@vulekamali.gov.za"
        discourse_sso_url: "https://discussions.vulekamali.gov.za/session/sso_login"
        env_name: prod
        media_hostname: media.vulekamali.gov.za
        postgres_database: budgetportal
        robots_deny_all: "false"
        sentry_dsn: "https://5999094b0e214151bdfef41a5ad513c2@sentry.io/1730285"
        solr_url: "http://solr.vulekamali.gov.za:8983/solr/budgetportal"
        tag_manager_id: "GTM-PLNL56L"
    salga-mobile-api:
      hosts:
        dokku9.code4sa.org:
      vars:
        app_domain: salga-mobile-api.openup.org.za
    gazettes_aleph:
      hosts:
        hetzner1.openup.org.za:
      vars:
        app_domain: search.opengazettes.org.za
