uct:
  hosts:
  vars:
    env_name: prod
    all_hosts_admins:
      - t0081785
  children:
    dokkus:
      hosts:
        srvubudoc001.uct.ac.za:
    "saldru-bps-cms":
      hosts:
        srvubudoc001.uct.ac.za:

all:
  hosts:
  vars:
    env_name: prod
    all_hosts_admins:
      - jdb
      - paulmwatson
      - dirk
      - rikusv
      - molotomt
    all_hosts_remove_admins:
      - adi
      - mila
      - otterbotter
    host_extra_admins: [] # Empty default - override this on specific hosts.
    host_remove_extra_admins: [] # Empty default - override this on specific hosts.
  children:
    elasticsearch:
      hosts:
        docker1.code4sa.org:
          ansible_user: ubuntu
    dokkus:
      hosts:
        dokku8.code4sa.org:
        dokku9.code4sa.org:
          host_extra_admins:
            - michael
        muni-portal-aws2.openup.org.za:
        pmg1-hetzner.openup.org.za:
        treasury1.openup.org.za:
        treasury4.openup.org.za:
          host_extra_admins:
            - michael
        treasury5.openup.org.za:
        hetzner1.openup.org.za:
          host_extra_admins:
            - michael
        aws1.keepthereceipt.org.za:
        idp1-aws.openup.org.za:
        pmg1-aws.pmg.org.za:
        elasticsearch1-aws.pmg.org.za:
        justice1-hetzner.openup.org.za:
        codebridge1-aws.openup.org.za:
        airflow1-hetzner.openup.org.za:
    ## App groups

    muni-portal-backend:
      hosts:
        muni-portal-aws2.openup.org.za:
      vars:
        app_domain: muni-portal-backend.openup.org.za
        frontend_base_url: https://app.capeagulhas.gov.za
        aws_storage_bucket_name: muni-portal-backend
        aws_s3_custom_domain: muni-portal-backend.s3.amazonaws.com
        media_url: https://muni-portal-backend.s3.amazonaws.com/
        collaborator_api_base_url: https://citizencollab.collaboratoronline.com

    procurement-portal-backend:
      hosts:
        aws1.keepthereceipts.org.za:
      vars:
        app_domain: data.keepthereceipts.org.za
        media_hostname: media.keepthereceipts.org.za
        env_name: prod

    "peoples-assembly":
      hosts:
        pmg1-hetzner.openup.org.za:

    "vulekamali":
      hosts:
        treasury4.openup.org.za:
          gunicorn_workers_arg: "--workers 2"
      vars:
        app_domain: vulekamali.gov.za
        ckan_domain: data.vulekamali.gov.za
        comments_enabled: "true"
        default_from_email: "info@vulekamali.gov.za"
        discourse_sso_url: "https://discussions.vulekamali.gov.za/session/sso_login"
        env_name: prod
        media_hostname: media.vulekamali.gov.za
        postgres_database: budgetportal
        robots_deny_all: "false"
        sentry_dsn: "https://5999094b0e214151bdfef41a5ad513c2@sentry.io/1730285"
        solr_url: "http://solr.vulekamali.gov.za:8983/solr/budgetportal"
        tag_manager_id: "GTM-PLNL56L"

    treasury-openspending:
      hosts: treasury5.openup.org.za
      vars:
        app_domain: openspending-dedicated.vulekamali.gov.za
        storage_bucket_name: openspending-vulekamali

    salga-mobile-api:
      hosts:
        dokku9.code4sa.org:
      vars:
        app_domain: salga-mobile-api.openup.org.za

    gazettes_aleph:
      hosts:
        hetzner1.openup.org.za:
      vars:
        app_domain: search.opengazettes.org.za

    adh-wazimap-uploaders:
      hosts:
        dokku9.code4sa.org:

    sanef-wazimap-uploaders:
      hosts:
        dokku9.code4sa.org:

    wazimap-ng:
      hosts:
        wazimapng1-aws.openup.org.za:
      vars:
        app_domain: production.wazimap-ng.openup.org.za
        aws_storage_bucket_name: wazimap-ng

    hackdash:
      hosts: codebridge1-aws.openup.org.za

    airflow:
      hosts: airflow1-hetzner.openup.org.za

    "osf-case-management":
      hosts:
        casefile.org.za:
      vars:
        app_domain: "casefile.org.za"
        app_url: "https://app.casefile.org.za"
        dashboard_url: "https://dashboard.casefile.org.za"
