all:
  hosts:
  vars:
    env_name: sandbox
    all_hosts_admins:
      - jdb
      - paulmwatson
      - michael
      - dirk
    all_hosts_remove_admins:
      - rikusv
      - adi
      - otterbotter
    host_extra_admins: [] # Empty default - override this on specific hosts.
    host_remove_extra_admins: [] # Empty default - override this on specific hosts.
  children:
    "osf-case-management":
      hosts:
        casefile.org.za:
      vars:
        app_domain: "sandbox.casefile.org.za"
        app_url: "https://sandbox-app.casefile.org.za"
        dashboard_url: "https://sandbox-dashboard.casefile.org.za"

    dokkus:
      hosts:
        dokku11.openup.org.za:
        casefile.org.za:

    "vulekamali":
      hosts:
        hetzner1.openup.org.za:
          host_extra_admins:
            - emre
      vars:
        app_domain: sandbox.vulekamali.gov.za
        ckan_domain: sandbox-data.vulekamali.gov.za
        comments_enabled: "false"
        default_from_email: "sandbox@vulekamali.gov.za"
        discourse_sso_url: "should-be-disabled"
        env_name: sandbox
        gunicorn_workers_arg: ""
        media_hostname: media.sandbox.vulekamali.gov.za
        robots_deny_all: "true"
        sentry_dsn: "https://acd93673a56a48939bef31fc9ad92f2c@sentry.io/1888207"
        solr_url: "http://solr:8983/solr/budgetportal-sandbox"
        tag_manager_id: ""
        openspending_dataset_create_suffix: "-sandbox"

    munimoney:
      hosts:
        dokku11.openup.org.za:
      vars:
        app_domain: sandbox.municipalmoney.gov.za
        no_index: "true"
        data_portal_url: "https://sandbox.data.municipalmoney.gov.za/"
        environment: "sandbox"

    nocodb:
      hosts:
        dokku11.openup.org.za:
      vars:
        app_domain: nocodb-sandbox.openup.org.za
        no_index: "true"
