all:
  hosts:
  vars:
    env_name: sandbox
    all_hosts_admins:
      - jdb
      - paulmwatson
      - dirk
      - rikusv
      - michael
    all_hosts_remove_admins:
      - adi
      - otterbotter
    host_extra_admins: [] # Empty default - override this on specific hosts.
    host_remove_extra_admins: [] # Empty default - override this on specific hosts.
  children:
    "osf-case-management":
      hosts:
        casefile.org.za:
      vars:
        app_domain: "sandbox.casefile.org.za"
        app_url: "https://sandbox-app.casefile.org.za"
        dashboard_url: "https://sandbox-dashboard.casefile.org.za"

    dokkus:
      hosts:
        casefile.org.za:
        
        
    "vulekamali":
      hosts:
        hetzner1.openup.org.za:
      vars:
        app_domain: sandbox.vulekamali.gov.za
        ckan_domain: sandbox-data.vulekamali.gov.za
        comments_enabled: "false"
        default_from_email: "sandbox@vulekamali.gov.za"
        discourse_sso_url: "should-be-disabled"
        env_name: sandbox
        gunicorn_workers_arg: ""
        media_hostname: media.sandbox.vulekamali.gov.za
        robots_deny_all: "true"
        sentry_dsn: "https://acd93673a56a48939bef31fc9ad92f2c@sentry.io/1888207"
        solr_url: "http://solr:8983/solr/budgetportal-sandbox"
        tag_manager_id: ""

    munimoney:
      hosts:
        dokku9.code4sa.org:
      vars:
        app_domain: sandbox.municipalmoney.gov.za
        no_index: "true"

    muni-portal-backend:
      hosts:
        muni-portal-aws2.openup.org.za:
      vars:
        app_domain: sandbox.muni-portal-backend.openup.org.za
        frontend_base_url: https://sandbox--cape-agulhas-app.netlify.app
        aws_storage_bucket_name: muni-portal-backend-sandbox
        aws_s3_custom_domain: muni-portal-backend-sandbox.s3.amazonaws.com
        media_url: https://muni-portal-backend-sandbox.s3.amazonaws.com/
        collaborator_api_base_url: https://citizencollab.collaboratoronline.com
