all:
  hosts:
    writeinpublic-test.pa.org.za:
      host_extra_admins:
        - delenamalan
  children:
    "vulekamali":
      hosts:
        hetzner1.openup.org.za:
      vars:
        env_name: sandbox
        app_domain: sandbox.vulekamali.gov.za
        postgres_database: budgetportal_sandbox
        robots_deny_all: "true"
        ckan_domain: sandbox-data.vulekamali.gov.za
        aws_storage_bucket_name: sandbox-media.vulekamali.gov.za
        comments_enabled: "false"
        solr_ur: "http://solr:8983/solr/budetportal-sandbox"
        sentry_dsn: "https://acd93673a56a48939bef31fc9ad92f2c@sentry.io/1888207"
        default_from_email: "sandbox@vulekamali.gov.za"
        discourse_sso_url: "should-be-disabled"

  vars:
    all_hosts_admins:
      - jdb
      - adi
      - lunga
      - dean
    host_extra_admins: [] # Empty default - override this on specific hosts.
