all:
  hosts:
  vars:
    env_name: staging
    all_hosts_admins:
      - jdb
      - paulmwatson
      - michael
      - dirk
    all_hosts_remove_admins:
      - rikusv
      - otterbotter
      - adi
    host_extra_admins: [] # Empty default - override this on specific hosts.
    host_remove_extra_admins: [] # Empty default - override this on specific hosts.
  children:
    "osf-case-management":
      hosts:
        casefile.org.za:
      vars:
        app_domain: "staging.casefile.org.za"
        app_url: "https://staging-app.casefile.org.za"
        dashboard_url: "https://staging-dashboard.casefile.org.za"

    dokkus:
      hosts:
        casefile.org.za:
        munimoney1-hetzner.openup.org.za:
        wazimapng1-aws.openup.org.za:
          host_extra_admins:
            - emre
            - gaurav

    ## App groups

    munimoney:
      hosts:
        dokku11.openup.org.za:
      vars:
        app_domain: staging.municipalmoney.gov.za
        no_index: "true"
        data_portal_url: "https://staging.data.municipalmoney.gov.za/"
        environment: "staging"

    wazimap-ng:
      hosts:
        wazimapng1-aws.openup.org.za:
      vars:
        app_domain: staging.wazimap-ng.openup.org.za
        aws_storage_bucket_name: wazimap-ng-staging
