all:
  hosts:
  vars:
    env_name: staging
    all_hosts_admins:
      - jdb
      - paulmwatson
      
      - rikusv
      - michael
    all_hosts_remove_admins:
      - otterbotter
      - adi
      - dirk
    host_extra_admins: [] # Empty default - override this on specific hosts.
    host_remove_extra_admins: [] # Empty default - override this on specific hosts.
  children:
    "osf-case-management":
      hosts:
        casefile.org.za:
      vars:
        app_domain: "staging.casefile.org.za"
        app_url: "https://staging-app.casefile.org.za"
        dashboard_url: "https://staging-dashboard.casefile.org.za"

    dokkus:
      hosts:
        casefile.org.za:
        munimoney1-hetzner.openup.org.za:
        wazimapng1-aws.openup.org.za:
          host_extra_admins:
            - emre
            - gaurav

    ## App groups

    munimoney:
      hosts:
        dokku9.code4sa.org:
      vars:
        app_domain: staging.municipalmoney.gov.za
        no_index: "true"

    muni-portal-backend:
      hosts:
        muni-portal-aws2.openup.org.za:
      vars:
        app_domain: staging.muni-portal-backend.openup.org.za
        frontend_base_url: https://staging--cape-agulhas-app.netlify.app
        aws_storage_bucket_name: muni-portal-backend-staging
        aws_s3_custom_domain: muni-portal-backend-staging.s3.amazonaws.com
        media_url: https://muni-portal-backend-staging.s3.amazonaws.com/
        collaborator_api_base_url: https://citizencollab.collaboratoronline.com

    wazimap-ng:
      hosts:
        wazimapng1-aws.openup.org.za:
      vars:
        app_domain: staging.wazimap-ng.openup.org.za
        aws_storage_bucket_name: wazimap-ng-staging
