all:
  hosts:
  vars:
    env_name: staging
    all_hosts_admins:
      - jdb
      - adi
      - dean
      - juriejan
      - otterbotter
    all_hosts_remove_admins: []
    host_extra_admins: [] # Empty default - override this on specific hosts.
    host_remove_extra_admins: [] # Empty default - override this on specific hosts.
  children:

    dokkus:
      hosts:
        munimoney1-hetzner.openup.org.za:

    munimoney:
      hosts:
        munimoney1-hetzner.openup.org.za:
      vars:
        app_domain: staging.municipalmoney.gov.za

    muni-portal-backend:
      hosts:
        muni-portal-aws2.openup.org.za:
      vars:
        app_domain: staging.muni-portal-backend.openup.org.za
