---
- hosts:
    - muni-portal-backend
  become: yes
  roles:
    - dokku_bot.ansible_dokku

  vars:
    instance_name: "muni-portal-backend-{{ env_name }}"
    app_name: "{{ instance_name }}"
    dokku_daemon_install: false # We install this using a dedicated playbook
    dokku_plugins:
      - name: letsencrypt
        url: https://github.com/dokku/dokku-letsencrypt.git

  tasks:

    - name: "Dokku app exists"
      dokku_app:
        app: "{{ app_name }}"
      tags:
        - app

    - name: "Install RDS CA Cert"
      ansible.builtin.copy:
        src: ../../files/certs/rds-ca-2019-root.pem
        dest: /var/
        owner: root
        group: root
        mode: '0644'
      tags:
        - app

    - name: "Mount RDS Certificate Authority Certificate where postgres expects it for deploy"
      dokku_docker_options:
        app: "{{ app_name }}"
        phase: deploy
        option: "-v /var/rds-ca-2019-root.pem:/home/django/.postgresql/root.crt"
      tags:
        - app

    - name: "Mount RDS Certificate Authority Certificate where postgres expects it for run"
      dokku_docker_options:
        app: "{{ app_name }}"
        phase: run
        option: "-v /var/rds-ca-2019-root.pem:/home/django/.postgresql/root.crt"
      tags:
        - app

    - name: "App nginx directory exists"
      file:
        path: "/home/dokku/{{ app_name }}/nginx.conf.d"
        state: directory
        mode: '0755'
        owner: dokku
        group: dokku
      tags:
        - app

    - name: "Upload file size is configured"
      copy:
        content: "client_max_body_size 100M;"
        dest: "/home/dokku/{{ app_name }}/nginx.conf.d/client_max_body_size.conf"
        owner: dokku
        group: dokku
        mode: "0644"
      register: nginx
      tags:
        - app

    - name: "Nginx is reloaded"
      service:
        name: nginx
        state: reloaded
      when: nginx.changed
      tags:
        - app

    - name: "Dokku app exists"
      dokku_app:
        app: "{{ app_name }}"
      tags:
        - app

    - name: "Dokku app config is set"
      vars:
        postgres_password: "{{ lookup('passwordstore', 'apps/muni-portal-backend/{{ env_name }}/POSTGRES')}}"
        postgres_hostname: "{{ lookup('passwordstore', 'apps/muni-portal-backend/{{ env_name }}/POSTGRES subkey=hostname')}}"
        postgres_username: "{{ lookup('passwordstore', 'apps/muni-portal-backend/{{ env_name }}/POSTGRES subkey=username')}}"
      dokku_config:
        app: "{{ app_name }}"
        config:
          CORS_ALLOWED_ORIGIN_REGEXES: "^https?://localhost:\\d+$,^https?://127.0.0.1:\\d+$,^https://app.capeagulhas.gov.za$,^https://cape-agulhas-app.openup.org.za$,^https://deploy-preview-\\d+--cape-agulhas-app.netlify.app$,^https://{{ env_name }}.app.capeagulhas.gov.za$,^https://{{ env_name }}--cape-agulhas-app.netlify.app$"
          DATABASE_URL: "postgres://{{ postgres_username }}:{{ postgres_password }}@{{ postgres_hostname }}:5432/muni_portal_{{ env_name }}?sslmode=verify-full"
          DJANGO_SECRET_KEY: "{{ lookup('passwordstore', 'apps/muni-portal-backend/{{ env_name }}/DJANGO_SECRET_KEY')}}"
          DOKKU_LETSENCRYPT_EMAIL: "webapps@openup.org.za"
          TAG_MANAGER_ENABLED: "False"
          AWS_STORAGE_BUCKET_NAME: "{{ aws_storage_bucket_name }}"
          AWS_SECRET_ACCESS_KEY: "{{ lookup('passwordstore', 'apps/muni-portal-backend/{{ env_name }}/AWS')}}"
          AWS_ACCESS_KEY_ID: "{{ lookup('passwordstore', 'apps/muni-portal-backend/{{ env_name }}/AWS subkey=AWS_ACCESS_KEY_ID')}}"
          AWS_S3_REGION_NAME: "eu-west-1"
          AWS_S3_CUSTOM_DOMAIN: "{{ aws_s3_custom_domain }}"
          MEDIA_URL: "{{ media_url }}"
          DEFAULT_FILE_STORAGE: "storages.backends.s3boto3.S3Boto3Storage"
          EMAIL_HOST_PASSWORD: "{{ lookup('passwordstore', 'apps/muni-portal-backend/{{ env_name }}/SMTP')}}"
          DEFAULT_FROM_EMAIL: "no-reply@capeagulhas.gov.za"
          FRONTEND_BASE_URL: "{{ frontend_base_url }}"
          WAGTAILAPI_BASE_URL: "https://{{ app_domain }}"
          SENTRY_DSN: "https://a5d3ce913bdd4eb594da36387b286d83@o242378.ingest.sentry.io/5496000"
          ENVIRONMENT: "{{ env_name }}"
          COLLABORATOR_API_USERNAME: "{{ lookup('passwordstore', 'apps/muni-portal-backend/{{ env_name}}/COLLABORATOR subkey=username') }}"
          COLLABORATOR_API_PASSWORD: "{{ lookup('passwordstore', 'apps/muni-portal-backend/{{ env_name}}/COLLABORATOR') }}"
          COLLABORATOR_API_BASE_URL: "{{ collaborator_api_base_url }}"
      tags:
        - app

    - name: "USER_ID build-arg is set"
      dokku_docker_options:
        app: "{{ app_name }}"
        phase: build
        option: "--build-arg USER_ID=1001"
      tags:
        - app

    - name: "GROUP_ID build-arg is set"
      dokku_docker_options:
        app: "{{ app_name }}"
        phase: build
        option: "--build-arg GROUP_ID=1001"
      tags:
        - app

    - name: "Dokku app domains are configured"
      dokku_domains:
        app: "{{ app_name }}"
        domains:
          - "{{ app_domain }}"
      tags:
        - app

    - name: "Your dokku git remote"
      debug:
        msg: "dokku@{{ inventory_hostname }}:{{ app_name }}"
      tags:
        - app
